disabled_rules:
    - switch_case_alignment
    - trailing_comma
    - trailing_whitespace
    - identifier_name
    - force_cast
    - force_try
reporter: "xcode"
excluded:
    - SystemUtils/Sources/SystemUtils/Secret.swift
