disabled_rules:
    - switch_case_alignment
    - trailing_comma
    - trailing_whitespace
force_cast: warning
force_try: warning
reporter: "xcode"
excluded:
    - SystemUtils/Sources/SystemUtils/Secret.swift
