version: '3'

tasks:
  build: xcodebuild -scheme Moc build
  clean: xcodebuild -scheme Moc clean
  release:
    cmds:
      - task: release:macOS
      - task: release:iPadOS
  release:macOS:
    cmds:
      - task: archive:macOS
      - cmd: cp result/Moc-macOS.xcarchive/Products/Applications/Moc.app result/Moc.app
  release:iPadOS:
    cmds:
      - task: archive:iPadOS
      - task: assemble-ipa
  archive:
    cmds:
      - task: archive:macOS
      - task: archive:iPadOS
      - task: assemble-ipa
  archive:macOS:
    cmds:
      - xcodebuild -scheme Moc archive -configuration release -sdk macosx -archivePath $ARCHIVE_PATH
    env:
      ARCHIVE_PATH: result/Moc-macOS.xcarchive
  archive:iPadOS:
    cmds:
        - xcodebuild -scheme Moc archive -configuration release -sdk iphoneos -archivePath $ARCHIVE_PATH
    env:
      ARCHIVE_PATH: result/Moc-iPadOS.xcarchive
  assemble-ipa:
    cmds:
        - xcodebuild -exportArchive -archivePath $ARCHIVE_PATH \
          -exportOptionsPlist iPadOS-export-options.plist \
          -exportPath $IPA_PATH
    env:
      ARCHIVE_PATH: result/Moc-iPadOS.xcarchive
      IPA_PATH: result/Moc.ipa
  generate:
    cmds:
      - task: generate:gyb
      - task: generate:sourcery
  generate:gyb:
    env:
      # Default values for macOS Telegram client
      API_ID: 2834
      API_HASH: 68875f756c9b437a8b916ca3de215815
      MACOS_APP_CENTER_SECRET: ""
      IPADOS_APP_CENTER_SECRET: ""
    cmds:
      - cmd: ./scripts/gyb.sh
        ignore_error: true
  generate:sourcery:
    cmds:
      - ./scripts/sourcery.sh