name: SwiftLint check

on:
    pull_request:
        branches: [ master ]
    workflow_dispatch:
    

jobs:
    check:
        name: Check code for possible issues with SwiftLint
        runs-on: ubuntu-latest
        
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Run SwiftLint
            uses: norio-nomura/action-swiftlint@3.2.1
            env:
              DIFF_BASE: ${{ github.base_ref }}
